#!/bin/bash

SRC=/shared/nil/mySnet
INS=/shared/nil/snetInstall


rm *.o *.a  DES

gcc  -I$INS/include/ -c desBoxes.c
gcc  -I$INS/include/ -c sosi.c
ar rcs libboxes.a desBoxes.o sosi.o

gcc -c -std=gnu99 -DPACKAGE_NAME=\"lpel\" -DPACKAGE_TARNAME=\"lpel\" -DPACKAGE_VERSION=\"1.x\" -DPACKAGE_STRING=\"lpel\ 1.x\" -DPACKAGE_BUGREPORT=\"daniel.prokesch@gmail.com\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PCL=1 -DUSE_MCTX_PCL=1 -DHAVE_PTHREAD=1 -DHAVE_SYSCONF=1 -DHAVE_PTHREAD_SPIN_INIT=1 -DHAVE_PTHREAD_SETAFFINITY_NP=1 -DHAVE_POSIX_SEMAPHORES=1 -DHAVE_POSIX_TIMERS=1 -DHAVE_SYNC_ATOMIC_BUILTINS=1 -DTLSSPEC=__thread -DHAVE___THREAD=1 -I. -I$SRC/lpel/include -I$SRC/lpel/src/include -g -O0 -Wall -pthread -c simpleDes.c -o simpleDes.o


gcc -std=gnu99 -g -O0 -Wall -pthread simpleDes.o -o DES -static -Wl,-llpel_hrc  -L$INS/lib/ -L. -Lboxes -lboxes $INS/lib/liblpel_hrc.a  $INS/lib/liblpel_mon.a $INS/lib/libpcl.a -lpthread -lrt -lm -pthread
